# Config file for automatic testing at travis-ci.org

sudo: false
language: python
python: 3.5
env:
  - TOX_ENV=quality-check
  - TOX_ENV=pypy3
  - TOX_ENV=pypy
  - TOX_ENV=py35
  - TOX_ENV=py34
  - TOX_ENV=py33
  - TOX_ENV=py27
  - TOX_ENV=docs

install:
  - pip install tox
  - pip install coveralls
script: tox -e $TOX_ENV
after_success:
  - if [[ $TOX_ENV == "quality-check" ]]; then
      coveralls;
    fi

before_cache:
  - rm -rf $HOME/.cache/pip/log
cache:
  directories:
    - $HOME/.cache/pip
